apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: server-app
  name: server-app
  namespace: d31
spec:
  containers:
  - image: nginx:1.18.0
    env:
      - name: USERNAME
        valueFrom: 
          secretKeyRef: 
            name: api-basic-auth
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: api-basic-auth
            key: password
    name: server-app
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
