apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: d2
  name: d2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: d2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: d2
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
